-- ============================================
-- GOLD LAYER TABLES
-- ============================================
--
-- Purpose:
-- Create Gold-layer tables containing
-- business-level summaries and metrics
-- derived from clean Silver-layer data.
--
-- Gold tables are designed for reporting,
-- analytics, and business decision-making.
-- ============================================

-- ============================================
-- PRODUCT SALES SUMMARY
-- ============================================

-- This table summarizes sales performance by product.
-- Each row represents one product and contains
-- aggregated metrics calculated from the Silver layer.

CREATE TABLE IF NOT EXISTS gold.product_sales_summary (
    
    -- Product identifier from the silver sales data.
    product_id VARCHAR(20) PRIMARY KEY,

    -- Total number of orders containing the product.
    total_orders INTEGER,

    -- Total number of units sold for the product.
    total_quantity INTEGER,

    -- Total sales revenue generated by the product.
    total_sales NUMERIC(12,2),

    -- Timestamp showing when the Gold summary was loaded.
    gold_load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);